import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#f8f9fa',
  },
  screen: {
    flex: 1,
    paddingHorizontal: 20,
    paddingVertical: 24,
    backgroundColor: 'transparent',
  },
  centered: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingVertical: 24,
    gap: 16,
    backgroundColor: 'transparent',
  },
  wordListScrollContent: {
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 0,
    gap: 10,
    backgroundColor: 'transparent',
  },
  levelsScreen: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  levelsScrollContent: {
    paddingHorizontal: 20,
    paddingVertical: 24,
    gap: 16,
    backgroundColor: 'transparent',
  },
  homeBackgroundLayer: {
    ...StyleSheet.absoluteFillObject,
  },
  homeBackgroundWash: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: '58%',
  },
  homeBackgroundBlobWarm: {
    position: 'absolute',
    width: 520,
    height: 520,
    borderRadius: 999,
    left: -170,
    top: -30,
    transform: [{ rotate: '-14deg' }],
  },
  homeBackgroundBlobCool: {
    position: 'absolute',
    width: 500,
    height: 500,
    borderRadius: 999,
    right: -180,
    bottom: -10,
    transform: [{ rotate: '16deg' }],
  },
  homeBackgroundRibbon: {
    position: 'absolute',
    left: '-12%',
    right: '-12%',
    top: '34%',
    height: 240,
    borderRadius: 48,
    transform: [{ rotate: '-8deg' }],
  },
  levelBackgroundLayer: {
    ...StyleSheet.absoluteFillObject,
  },
  backgroundGlow: {
    position: 'absolute',
    width: 260,
    height: 260,
    borderRadius: 999,
    backgroundColor: 'rgba(255, 214, 0, 0.11)',
  },
  backgroundGlowLeft: {
    top: 120,
    left: -40,
  },
  backgroundGlowRight: {
    right: -30,
    bottom: 140,
    backgroundColor: 'rgba(0, 200, 83, 0.11)',
  },
  floatingArticle: {
    position: 'absolute',
    color: '#1f2937',
    opacity: 0.18,
    fontWeight: '800',
    letterSpacing: 1,
    textShadowColor: 'rgba(255,255,255,0.5)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 6,
  },
  loadingTitle: {
    color: '#1f2a37',
    fontSize: 34,
    fontWeight: '800',
  },
  loadingSubtitle: {
    marginTop: 8,
    color: '#6b7280',
    fontSize: 16,
  },
  heroCard: {
    borderRadius: 28,
    padding: 24,
    backgroundColor: '#fffaf3',
    borderWidth: 1,
    borderColor: '#eadcc8',
    shadowColor: '#d9c9b4',
    shadowOpacity: 0.3,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
  },
  eyebrow: {
    color: '#a16207',
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  heroTitle: {
    marginTop: 10,
    color: '#1f2937',
    fontSize: 34,
    fontWeight: '800',
  },
  heroSubtitle: {
    marginTop: 10,
    color: '#4b5563',
    fontSize: 16,
    lineHeight: 24,
  },
  logoWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 0,
    marginBottom: 4,
  },
  homeLogo: {
    width: '100%',
    height: 284,
  },
  menuColumn: {
    flex: 1,
    justifyContent: 'center',
    gap: 14,
  },
  homeMenuGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 14,
    alignContent: 'flex-start',
  },
  homeStartWrap: {
    marginBottom: 12,
  },
  homeStartButton: {
    borderRadius: 22,
  },
  gradientButtonShell: {
    borderRadius: 22,
    overflow: 'hidden',
    shadowColor: 'rgba(22, 24, 29, 0.95)',
    shadowOpacity: 0.24,
    shadowRadius: 10,
    shadowOffset: { width: -5, height: 5 },
    elevation: 4,
  },
  gradientButtonShellSmall: {
    minWidth: 118,
  },
  gradientButtonShellSquare: {
    width: '47.7%',
    aspectRatio: 1,
  },
  gradientButtonFill: {
    paddingVertical: 19,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  gradientButtonAnimatedWrap: {
    position: 'relative',
    overflow: 'hidden',
  },
  gradientButtonAnimatedTrack: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: '-60%',
    width: '220%',
  },
  gradientButtonAnimatedFill: {
    width: '100%',
    height: '100%',
  },
  gradientButtonFillSmall: {
    paddingVertical: 10,
    paddingHorizontal: 14,
  },
  gradientButtonFillTall: {
    paddingVertical: 28,
  },
  gradientButtonFillSquare: {
    flex: 1,
    paddingVertical: 16,
    paddingHorizontal: 14,
  },
  gradientButtonText: {
    fontSize: 16,
    fontWeight: '800',
    textAlign: 'center',
  },
  gradientButtonTextOverlay: {
    zIndex: 1,
  },
  gradientButtonTextSmall: {
    fontSize: 12,
  },
  gradientButtonTextSquare: {
    fontSize: 20,
  },
  gradientButtonTextTall: {
    fontSize: 18,
  },
  primaryButton: {
    borderRadius: 22,
    backgroundColor: '#f59e0b',
    paddingVertical: 18,
    paddingHorizontal: 20,
    alignItems: 'center',
    shadowColor: '#f59e0b',
    shadowOpacity: 0.25,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  primaryButtonText: {
    color: '#ffffff',
    fontSize: 17,
    fontWeight: '800',
  },
  secondaryButton: {
    borderRadius: 22,
    backgroundColor: '#ffffff',
    paddingVertical: 16,
    paddingHorizontal: 20,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e5d8c7',
  },
  secondaryButtonText: {
    color: '#1f2937',
    fontSize: 16,
    fontWeight: '700',
  },
  sectionTitle: {
    color: '#1f2937',
    fontSize: 30,
    fontWeight: '800',
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  sectionHeaderBackWrap: {
    minWidth: 104,
  },
  levelHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginTop: -10,
    marginBottom: -18,
  },
  levelCard: {
    borderRadius: 24,
    overflow: 'hidden',
    shadowColor: '#d1c1ae',
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  levelGradient: {
    padding: 22,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  levelTitle: {
    fontSize: 24,
    fontWeight: '800',
  },
  levelSubtitle: {
    fontSize: 15,
    lineHeight: 22,
    marginTop: 6,
    maxWidth: 220,
  },
  levelMeta: {
    fontSize: 13,
    fontWeight: '700',
  },
  wordBadgeWrap: {
    width: 132,
    height: 132,
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: -18,
  },
  wordBadgeStar: {
    position: 'absolute',
    width: 132,
    height: 132,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#f0b429',
    shadowOpacity: 0.18,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  wordBadgeStarText: {
    color: '#f59e0b',
    fontSize: 106,
    lineHeight: 108,
    fontWeight: '800',
  },
  wordBadgeLabelTop: {
    color: '#8a5a00',
    fontSize: 20,
    fontWeight: '900',
    textAlign: 'center',
    lineHeight: 22,
  },
  wordBadgeLabelBottom: {
    color: '#8a5a00',
    fontSize: 13,
    fontWeight: '800',
    textAlign: 'center',
    lineHeight: 15,
  },
  wordListLevelGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
  },
  wordListLevelCard: {
    width: '47.5%',
    aspectRatio: 1,
    borderRadius: 24,
    overflow: 'hidden',
    shadowColor: '#d1c1ae',
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  wordListLevelGradient: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
  },
  wordListLevelTitle: {
    fontSize: 34,
    fontWeight: '800',
    letterSpacing: 1,
  },
  gameTopBar: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginBottom: 12,
  },
  menuSmallButton: {
    borderRadius: 16,
    backgroundColor: '#ffffff',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: '#e4d8cb',
  },
  menuSmallButtonText: {
    color: '#1f2937',
    fontWeight: '700',
    fontSize: 12,
  },
  gameInfoRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 14,
  },
  gameInfoCard: {
    flex: 1,
    borderRadius: 22,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#eadcc8',
    paddingVertical: 14,
    paddingHorizontal: 16,
    shadowColor: '#d1c1ae',
    shadowOpacity: 0.12,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  gameInfoLevelShell: {
    flex: 1,
    borderRadius: 22,
    overflow: 'hidden',
    shadowColor: '#d1c1ae',
    shadowOpacity: 0.16,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 3,
  },
  gameInfoLevelCard: {
    borderRadius: 22,
    paddingVertical: 14,
    paddingHorizontal: 16,
  },
  gameInfoLabel: {
    color: '#8b5e34',
    fontSize: 11,
    textTransform: 'uppercase',
    fontWeight: '800',
    letterSpacing: 0.7,
  },
  gameInfoValue: {
    marginTop: 6,
    color: '#111827',
    fontSize: 24,
    fontWeight: '900',
  },
  gameInfoLevelLabel: {
    color: '#ecfdf5',
  },
  gameInfoLevelValue: {
    color: '#ffffff',
  },
  gameStatsRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 18,
  },
  gameStatCard: {
    flex: 1,
    borderRadius: 20,
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderWidth: 1,
    alignItems: 'center',
    shadowColor: '#d1c1ae',
    shadowOpacity: 0.12,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  gameStatCardBlue: {
    backgroundColor: '#eef6ff',
    borderColor: '#bfdbfe',
  },
  gameStatCardGold: {
    backgroundColor: '#fff7e6',
    borderColor: '#fde68a',
  },
  gameStatCardRose: {
    backgroundColor: '#fff1f2',
    borderColor: '#fecdd3',
  },
  gameStatCardTeal: {
    backgroundColor: '#ecfeff',
    borderColor: '#99f6e4',
  },
  gameStatLabel: {
    color: '#6b7280',
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  gameStatValue: {
    marginTop: 6,
    color: '#111827',
    fontSize: 24,
    fontWeight: '900',
  },
  questionArea: {
    position: 'relative',
  },
  confettiLayer: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    width: 0,
    height: 0,
    zIndex: 2,
  },
  confettiPiece: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: 12,
    height: 20,
    borderRadius: 4,
  },
  questionCard: {
    backgroundColor: '#ffffff',
    borderRadius: 28,
    paddingHorizontal: 24,
    paddingVertical: 30,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#eadcc8',
  },
  developerVisualCard: {
    width: 124,
    height: 124,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
    shadowColor: '#d1c1ae',
    shadowOpacity: 0.16,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  developerVisualEmoji: {
    fontSize: 60,
  },
  articleRevealBadge: {
    marginTop: 12,
    borderRadius: 999,
    paddingHorizontal: 18,
    paddingVertical: 7,
    borderWidth: 1,
  },
  articleRevealText: {
    fontSize: 22,
    fontWeight: '900',
    textTransform: 'lowercase',
  },
  findWrongQuestionLabel: {
    color: '#8b5e34',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
    textAlign: 'center',
  },
  questionTranslation: {
    marginTop: 4,
    color: '#4b5563',
    fontSize: 15,
    fontWeight: '700',
    textAlign: 'center',
  },
  wordText: {
    marginTop: 12,
    color: '#111827',
    fontSize: 42,
    fontWeight: '800',
    textAlign: 'center',
  },
  answerColumn: {
    gap: 12,
    marginTop: 18,
  },
  answerButton: {
    borderRadius: 22,
    borderWidth: 2,
    paddingVertical: 20,
    alignItems: 'center',
  },
  answerButtonCorrect: {
    opacity: 0.88,
  },
  answerButtonWrong: {
    opacity: 0.82,
  },
  answerText: {
    fontSize: 24,
    fontWeight: '800',
    color: '#ffffff',
  },
  wordGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  wordListModeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
  },
  wordListTopActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  wordFilterGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  wordArticleFilterGrid: {
    flexDirection: 'row',
    flexWrap: 'nowrap',
    justifyContent: 'space-between',
    gap: 8,
  },
  wordLevelFilterGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  wordFilterCardShell: {
    width: '23%',
    aspectRatio: 1,
    borderRadius: 18,
    overflow: 'hidden',
    shadowColor: '#cbd5e1',
    shadowOpacity: 0.18,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  wordArticleFilterCardShell: {
    width: '31%',
    aspectRatio: 1,
    borderRadius: 18,
    overflow: 'hidden',
    shadowColor: '#cbd5e1',
    shadowOpacity: 0.18,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  wordLevelFilterCardShell: {
    width: '48%',
    aspectRatio: 1,
    borderRadius: 18,
    overflow: 'hidden',
    shadowColor: '#cbd5e1',
    shadowOpacity: 0.18,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  wordFilterCard: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 8,
  },
  wordFilterCardText: {
    color: '#ffffff',
    fontSize: 20,
    fontWeight: '900',
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  wordFilterInfoBadge: {
    width: 40,
    height: 40,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.18)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.45)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  wordFilterInfoText: {
    color: '#ffffff',
    fontSize: 22,
    fontWeight: '900',
    textAlign: 'center',
  },
  wordListPagination: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    marginVertical: 4,
  },
  wordListPageBadge: {
    flex: 1,
    minHeight: 54,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
    shadowColor: '#94a3b8',
    shadowOpacity: 0.18,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  wordListPageText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '800',
    textAlign: 'center',
  },
  wordCard: {
    width: '100%',
    height: '100%',
    aspectRatio: undefined,
    flex: 1,
    borderRadius: 20,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
    overflow: 'hidden',
  },
  wordCardPressable: {
    width: '23%',
    aspectRatio: 1,
  },
  wordCardFlipContainer: {
    flex: 1,
    position: 'relative',
  },
  wordCardFace: {
    ...StyleSheet.absoluteFillObject,
    backfaceVisibility: 'hidden',
  },
  wordCardBackFace: {
    paddingHorizontal: 12,
  },
  wordCardTranslation: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '800',
    textAlign: 'center',
    textShadowColor: 'rgba(0, 0, 0, 0.14)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
    lineHeight: 17,
  },
  wordCardBack: {
    width: '23%',
    aspectRatio: 1,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#eadcc8',
    shadowColor: '#cbd5e1',
    shadowOpacity: 0.18,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  wordCardBackInner: {
    flex: 1,
    borderRadius: 16,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#eadcc8',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#d1c1ae',
    shadowOpacity: 0.12,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
  },
  wordCardLevelText: {
    color: '#ffffff',
    fontSize: 10,
    fontWeight: '900',
    marginBottom: 6,
    opacity: 0.95,
  },
  wordCardArticle: {
    fontSize: 14,
    fontWeight: '900',
    textTransform: 'lowercase',
    color: '#ffffff',
    textShadowColor: 'rgba(0, 0, 0, 0.12)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  wordCardWord: {
    marginTop: 4,
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '800',
    textAlign: 'center',
    textShadowColor: 'rgba(0, 0, 0, 0.14)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  backArrowText: {
    color: '#1f2937',
    fontSize: 28,
    fontWeight: '800',
    lineHeight: 30,
  },
  statGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 14,
  },
  statCard: {
    flexBasis: '48%',
    flexGrow: 1,
    borderRadius: 24,
    padding: 18,
    paddingTop: 22,
    backgroundColor: 'rgba(255, 255, 255, 0.94)',
    borderWidth: 1,
    borderColor: '#efe1cf',
    shadowColor: 'rgba(96, 73, 42, 0.14)',
    shadowOpacity: 0.18,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
    position: 'relative',
    overflow: 'hidden',
  },
  statCardTopBar: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 6,
  },
  statMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  statAccentDot: {
    width: 10,
    height: 10,
    borderRadius: 999,
  },
  statLabel: {
    color: '#7c5b34',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.7,
    textTransform: 'uppercase',
  },
  statValue: {
    fontSize: 30,
    fontWeight: '800',
  },
  statValueWrap: {
    marginTop: 14,
    borderRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 14,
    backgroundColor: 'rgba(255, 255, 255, 0.72)',
  },
  panel: {
    borderRadius: 22,
    padding: 20,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#eadcc8',
  },
  panelTitle: {
    color: '#1f2937',
    fontSize: 20,
    fontWeight: '800',
    marginBottom: 8,
  },
  panelTitleNoMargin: {
    color: '#1f2937',
    fontSize: 20,
    fontWeight: '800',
  },
  panelText: {
    color: '#4b5563',
    fontSize: 15,
    lineHeight: 24,
  },
  levelPerformanceRow: {
    marginTop: 14,
    paddingBottom: 2,
  },
  levelPerformanceHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  levelPerformanceTitleWrap: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 10,
  },
  levelPerformanceLevel: {
    color: '#1f2937',
    fontSize: 17,
    fontWeight: '800',
  },
  levelPerformanceMeta: {
    color: '#7c6a55',
    fontSize: 13,
    fontWeight: '700',
  },
  levelPerformanceRatio: {
    color: '#8b5e34',
    fontSize: 15,
    fontWeight: '800',
  },
  levelPerformanceTrack: {
    height: 12,
    borderRadius: 999,
    backgroundColor: '#f4eadb',
    overflow: 'hidden',
  },
  levelPerformanceFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: '#f59e0b',
  },
  settingHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 10,
  },
  settingIconText: {
    color: '#a16207',
    fontSize: 22,
    fontWeight: '800',
  },
  toggleRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 8,
  },
  optionButton: {
    flex: 1,
    borderRadius: 16,
    paddingVertical: 14,
    alignItems: 'center',
    backgroundColor: '#fffaf3',
    borderWidth: 1,
    borderColor: '#eadcc8',
  },
  optionButtonActive: {
    backgroundColor: '#f59e0b',
    borderColor: '#f59e0b',
  },
  optionButtonText: {
    color: '#1f2937',
    fontWeight: '700',
  },
  optionButtonTextActive: {
    color: '#ffffff',
  },
});
